apps/bitcoin_web/lib/bitcoin_web/router.ex
defmodule BitcoinWeb.Router do
  use BitcoinWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BitcoinWeb do
    pipe_through :browser

    get "/", PageController, :index

    scope "/stats" do
      get "/", StatsController, :index
    end

    scope "/public-key" do
      resources "/", PublicKeyController, only: [:index, :new]
      get "/display", PublicKeyController, :display
      post "/display", PublicKeyController, :display
    end

    scope "/private-key" do
      resources "/", PrivateKeyController, only: [:index]
      get "/parse", PrivateKeyController, :parse
      get "/display", PrivateKeyController, :display
      post "/display", PrivateKeyController, :display
      get "/sign_message", PrivateKeyController, :sign_message
      get "/convert", PrivateKeyController, :convert
    end

    scope "/signature" do
      resources "/", SignatureController, only: [:index, :new]
      get "/parse", SignatureController, :parse
      get "/display", SignatureController, :display
      post "/display", SignatureController, :display
      get "/verify", SignatureController, :verify
    end

    scope "/transaction" do
      get "/", TransactionController, :index
      get "/display", TransactionController, :display
      post "/display", TransactionController, :display
      get "/parse", TransactionController, :parse
      get "/verify", TransactionController, :verify
    end

    scope "/encoder" do
      get "/", EncoderController, :index
      get "/sha256", EncoderController, :sha256
      post "/sha256", EncoderController, :sha256
      get "/ripemd160", EncoderController, :ripemd160
      post "/ripemd160", EncoderController, :ripemd160
      get "/hash160", EncoderController, :hash160
      post "/hash160", EncoderController, :hash160
      get "/hex", EncoderController, :hex
      post "/hex", EncoderController, :hex
      get "/base58", EncoderController, :base58
      post "/base58", EncoderController, :base58
      get "/base64", EncoderController, :base64
      post "/base64", EncoderController, :base64
      get "/bech32", EncoderController, :bech32
      post "/bech32", EncoderController, :bech32
    end

    scope "/extended-key" do
      get "/", ExtendedKeyController, :index
      # get "/from-seed", ExtendedKeyController, :seed_to_xprv
      get "/derive", ExtendedKeyController, :derive
      get "/parse", ExtendedKeyController, :parse
      get "/convert", ExtendedKeyController, :convert
      get "/display", ExtendedKeyController, :display
      post "/display", ExtendedKeyController, :display
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", BitcoinWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BitcoinWeb.Telemetry
    end
  end
end

apps/bitcoin_web/lib/bitcoin_web/controllers/encoder_controller.ex
defmodule BitcoinWeb.EncoderController do
  use BitcoinWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html", 
          options: BitcoinWeb.EncoderView.all_items(),
          option: BitcoinWeb.PageView.get_option("encoder"))
  end

  def sha256(conn, %{"data" => data, "hex" => hex}) do
    data = String.trim(data)
    if data != "" do
      case dehexify(data, hex) do
        {:ok, data} -> 
          res = Bitcoin.Encoder.sha256(data)
          render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:sha256), data: data, result: res)
        {:error, _} ->
          conn
          |> put_flash(:error, "data is not proper hex")
          |> render("new.html", option: BitcoinWeb.EncoderView.get_option(:sha256), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:sha256), result: nil)
    end
  end
  def sha256(conn, _params) do
    render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:sha256), result: nil)
  end

  def ripemd160(conn, %{"data" => data, "hex" => hex}) do
    data = String.trim(data)
    if data != "" do
      case dehexify(data, hex) do
        {:ok, data} -> 
          res = Bitcoin.Encoder.ripemd160(data)
          render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:ripemd160), data: data, result: res)
        {:error, _} ->
          conn
          |> put_flash(:error, "data is not proper hex")
          |> render("new.html", option: BitcoinWeb.EncoderView.get_option(:ripemd160), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:ripemd160), result: nil)
    end
  end
  def ripemd160(conn, _params) do
    render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:ripemd160), result: nil)
  end

  def hash160(conn, %{"data" => data, "hex" => hex}) do
    data = String.trim(data)
    if data != "" do
      case dehexify(data, hex) do
        {:ok, data} -> 
          res = Bitcoin.Encoder.hash160(data)
          render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:hash160), data: data, result: res)
        {:error, _} ->
          conn
          |> put_flash(:error, "data is not proper hex")
          |> render("new.html", option: BitcoinWeb.EncoderView.get_option(:hash160), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:hash160), result: nil)
    end
  end
  def hash160(conn, _params) do
    render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:hash160), result: nil)
  end

  def hex(conn, %{"data" => data, "encode" => encode}) do
    data = String.trim(data)
    if data != "" do
      case process_data(data, encode, :hex) do
        {:ok, res} ->
          render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:hex), data: data, result: res)
        {:error, msg} ->
          conn
          |> put_flash(:error, "invalid data: " <> msg)
          |> render( "new.html", option: BitcoinWeb.EncoderView.get_option(:hex), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:hex), result: nil)
    end
  end
  def hex(conn, _params) do
    render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:hex), result: nil)
  end

  def base58(conn, %{"data" => data, "encode" => encode}) do
    data = String.trim(data)
    if data != "" do
      case process_data(data, encode, :base58) do
        {:ok, res} -> 
          render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:base58), data: data, result: res)
        {:error, msg} ->
          conn
          |> put_flash(:error, "invalid data: " <> msg)
          |> render( "new.html", option: BitcoinWeb.EncoderView.get_option(:base58), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:base58), result: nil)
    end
  end
  def base58(conn, _params) do
    render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:base58), result: nil)
  end

  def base64(conn, %{"data" => data, "encode" => encode}) do
    data = String.trim(data)
    if data != "" do
      case process_data(data, encode, :base64) do
        {:ok, res} -> 
          render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:base64), data: data, result: res)
        {:error, msg} ->
          conn
          |> put_flash(:error, "invalid data: " <> msg)
          |> render( "new.html", option: BitcoinWeb.EncoderView.get_option(:base64), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:base64), result: nil)
    end
  end
  def base64(conn, _params) do
    render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:base64), result: nil)
  end


  # 000e140f070d1a001912060b0d081504140311021d030c1d03040f1814060e1e16
  
  def bech32(conn, %{"data" => data, "encode" => "false", "network" => network}) do
    hrp = case network do
      "bitcoin-mainnet" -> "bc"
      "bitcoin-testnet" -> "tb"
      "lightning-mainnet" -> "lnbc"
      "lightning-testnet" -> "lntb"
      "lightning-signet" -> "lntbs"
      "lightning-regtest" -> "lnbcrt"
    end

    data = String.trim(data)
    if data != "" do
      case Bitcoin.Encoder.to_bech32(hrp, data) do
        {:ok, res} -> 
          render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:bech32), data: data, hrp: hrp, result: res)
        {:error, msg} ->
          conn
          |> put_flash(:error, "invalid data: " <> msg)
          |> render( "new.html", option: BitcoinWeb.EncoderView.get_option(:bech32), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:bech32), result: nil)
    end
  end
  def bech32(conn, %{"data" => data, "encode" => "true", "network" => network}) do
    data = String.trim(data)
    if data != "" do
      case Bitcoin.Encoder.from_bech32(data) do
        {:ok, bech_version, hrp, hex} -> 
          render(conn, "new.html", 
            option: BitcoinWeb.EncoderView.get_option(:bech32), 
            bech_version: bech_version,
            hrp: hrp,
            result: hex,
            data: data)
        {:error, msg} ->
          conn
          |> put_flash(:error, "invalid data: " <> msg)
          |> render( "new.html", option: BitcoinWeb.EncoderView.get_option(:bech32), result: nil)
      end
    else
      render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:bech32), result: nil)
    end
  end
  def bech32(conn, _params) do
    render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:bech32), result: nil)
  end
  

  # def bech32(conn, %{"data" => data}) do
  #   render(conn, "new.html", option: BitcoinWeb.EncoderView.get_option(:bech32))
  # end

  defp dehexify(data, "false"), do: {:ok, data}
  defp dehexify(data, "true") do
    data = String.downcase(data)
    case Base.decode16(data, case: :lower) do
      {:ok, new_data} -> {:ok, new_data}
      :error -> {:error, "bad hex"}
    end
  end

  defp process_data(data, encode, scheme) do
    case {scheme, encode} do
      {:hex, "false"} -> Bitcoin.Encoder.to_hex(data)
      {:hex, "true"} -> Bitcoin.Encoder.from_hex(data)

      {:base58, "true"} -> Bitcoin.Encoder.from_base58(data)
      {:base58, "false"} -> Bitcoin.Encoder.to_base58(data)

      {:base64, "true"} -> Bitcoin.Encoder.from_base64(data)
      {:base64, "false"} -> Bitcoin.Encoder.to_base64(data)

      {:bech32, "true"} -> {:error, "unimplemented"}
      {:bech32, "false"} -> {:error, "unimplemented"}
      {:bech32m, "true"} -> {:error, "unimplemented"}
      {:bech32m, "false"} -> {:error, "unimplemented"}
    end
  end

end

apps/bitcoin_web/lib/bitcoin_web/views/encoder_view.ex
defmodule BitcoinWeb.EncoderView do
  use BitcoinWeb, :view

  @page_description "Tools to encode and decode data using Bitcoin's encoding schemes."

  @opts [
    %{name: :sha256, form: :hash, title: "SHA-256", description: "Calculate the SHA-256 hash of any data."},
    %{name: :ripemd160, form: :hash, title: "RIPEMD160", description: "Calculate the RIPEMD160 hash of any data."},
    %{name: :hash160, form: :hash, title: "Hash160", description: "Calculate the Hash160 hash of any data."},
    %{name: :hex, form: :encoding, title: "Base16 (Hex)", description: "Encode and decode to and from Base16 (hex)."},
    %{name: :base58, form: :encoding, title: "Base58", description: "Encode and decode to and from Base58."},
    %{name: :base64, form: :encoding, title: "Base64", description: "Encode and decode to and from Base64."},
    %{name: :bech32, form: :bech32, title: "Bech32", description: "Encode and decode to and from Bech32 and Bech32m."},
	]

  def all_items, do: @opts

  def get_option(name_a) do
    Enum.find(@opts, &(&1.name) == name_a)
  end

  def page_description, do: @page_description

end

# BECH32 decoding does not yield witness program directly.
# 000e140f070d1a001912060b0d081504140311021d030c1d03040f1814060e1e16
# bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4

apps/bitcoin_web/lib/bitcoin_web/templates/encoder/_bech32_form.html.eex
<%= form_for @conn, @action, fn f -> %>

	<%= label f, :data %>
	<%= text_input f, :data, required: true %>
	<%= error_tag f, :data %>

	<p class="nb">This field encodes 5-bit hex data, not witness program hex. Use the Address or Lightning Modules.</p>

	<%= label f, :"encode / decode" %>
	<label class="switch">
	  <%= checkbox f, :encode %>
	  <span class="slider round"></span>
	</label>

	<%= label f, :network %>
	<input required checked="checked" style="display: inline;" type="radio" id="bitcoin-mainnet" name="network" value="bitcoin-mainnet"
	>  <label class="data-option data-inline" for="bitcoin-mainnet">Bitcoin Mainnet</label><br>
	<input style="display: inline;" type="radio" id="bitcoin-testnet" name="network" value="bitcoin-testnet"
	>  <label class="data-option data-inline" for="bitcoin-testnet">Bitcoin Testnet</label><br>
	<input style="display: inline;" type="radio" id="lightning-mainnet" name="network" value="lightning-mainnet"
	>  <label class="data-option data-inline" for="lightning-mainnet">Lightning Mainnet</label><br>
	<input style="display: inline;" type="radio" id="lightning-testnet" name="network" value="lightning-testnet"
	>  <label class="data-option data-inline" for="lightning-testnet">Lightning Testnet</label><br>
	<input style="display: inline;" type="radio" id="lightning-signet" name="network" value="lightning-signet"
	>  <label class="data-option data-inline" for="lightning-signet">Lightning Signet</label><br>
	<input style="display: inline;" type="radio" id="lightning-regtest" name="network" value="lightning-regtest"
	>  <label class="data-option data-inline" for="lightning-regtest">Lightning Regtest</label><br>
	<div>
		<%= submit "encode / decode" %>
	</div>
<% end %>

apps/bitcoin_web/lib/bitcoin_web/templates/encoder/_encoding_form.html.eex
<%= form_for @conn, @action, fn f -> %>

	<%= label f, :data %>
	<%= text_input f, :data, required: true %>
	<%= error_tag f, :data %>

	<%= label f, :"encode / decode" %>
	<label class="switch">
	  <%= checkbox f, :encode %>
	  <span class="slider round"></span>
	</label>

	<div>
		<%= submit "encode / decode" %>
	</div>
<% end %>

apps/bitcoin_web/lib/bitcoin_web/templates/encoder/_hash_form.html.eex
<%= form_for @conn, @action, fn f -> %>

	<%= label f, :data %>
	<%= text_input f, :data, required: true %>
	<%= error_tag f, :data %>

	<%= label f, :hex %>
	<label class="switch">
	  <%= checkbox f, :hex %>
	  <span class="slider round"></span>
	</label>

	<div>
		<%= submit "digest" %>
	</div>
<% end %>

apps/bitcoin_web/lib/bitcoin_web/templates/encoder/index.html.eex
<%= render(BitcoinWeb.SharedView, "_subnav.html", subnav_items: [
			%{text: "home", to: Routes.page_path(@conn, :index)}
		])
	%>
	
<article class="content">
		<%= render(BitcoinWeb.SharedView, "_header.html", title: "Encoder Options") %>
		<ul class="item-list">
      <%= for option <- @options do %>
        <li>
          <%= render(BitcoinWeb.SharedView, "_item_card.html", to: Routes.encoder_path(@conn, option.name), option: option) %>
        </li>
      <% end %>
    </ul>
</article>

apps/bitcoin_web/lib/bitcoin_web/templates/encoder/new.html.eex
<%= render(BitcoinWeb.SharedView, "_subnav.html", subnav_items: [
				%{text: "home", to: Routes.page_path(@conn, :index)},
				%{text: "encoder home", to: Routes.encoder_path(@conn, :index)},
			])
		%>

<article class="content">
		<%= render(BitcoinWeb.SharedView, "_header.html", title: "Encoding: #{@option.title}") %>

		<%= render("_#{@option.form}_form.html", conn: @conn, action: Routes.encoder_path(@conn, @option.name)) %>

		<%= if @result != nil do %>
		<p>Result:</p>
		<p><%= @result %>
		<%= render(BitcoinWeb.SharedView, "_copy_to_clipboard.html", conn: @conn, data: @result) %></p>
		<% end %>

</article>